package io.curiositycore.thecuriositycore.database.util.exceptions;